### ISSUE TITLE
Gnome 44.1 point release is out

### ISSUE THREAD

**Issue by Scotty-Trees** [flathub/org.gnome.Connections#9]
Greetings,

Just wanted to inform the maintainers that Gnome 44.1 point release was just pushed out on Fedora 38 today. Many flatpaks in the Gnome stack are already updated to their 44/44.1 components, but Gnome Connections flatpak (and Gnome Calendar flatpak too) are still using older 44 versions. Just wanted to see if the maintainers could bump to the latest point release when time is permitted of course, thank you. Cheers.

**Comment by A6GibKm** [comment]
My advice would be to send a PR yourself. You just have to edit these two lines with the correct value https://github.com/flathub/org.gnome.Connections/blob/master/org.gnome.Connections.json#L70-L71, and test that the apps boot correctly.

**Comment by Scotty-Trees** [comment]
I've never actually tried doing a PR request before. I'll give it a go, just know I have no idea what I'm doing (not a coder), but I'll try my best to figure it out right now and see if I can come up with anything.

**Comment by A6GibKm** [comment]
Check other commits like https://github.com/flathub/org.gnome.Connections/commit/6cb1bbbc07c867f42a5f822940e7d17d98507052 for example. For the moment the bot will build the flatpak for you and you can use that to test. If you have further questions drop by the flatpak channel at matrix.

**Comment by Scotty-Trees** [comment]
My knowledge of GitHub is unfortunately limited to just bug reporting. And even that for me is not always easy task with tracking down information and causes and what not. I tried spending an hour yesterday trying to figure out merge requests, and where to look and where to put things between commits, json files, merge histories, but I just couldn't teach myself something I just don't understand, if that makes sense. 

I do appreciate you providing your insights, but unfortunately nearly all of it is over my head.

**Comment by A6GibKm** [comment]
I already opened a PR #11, but if you are interested you would have to learn a bit about git,

If this is a simple change, use github edit ui using the edit (pencil) button here

![image](https://user-images.githubusercontent.com/11528996/235318537-b616c166-3c43-4fd1-a197-482d969c5fac.png)

if it is not a simple change it goes like this

- fork the code using github's ui
- get the code you want **from your fork** using `git clone`
- edit the code to do what you want
- commit your changes using `git commit`
- push your changes to your fork using `git push`
- open a PR using github ui

In this particular case I already did it

In this particular case, you would have to look at https://gitlab.gnome.org/GNOME/connections/-/tags and copy the commit (4f2b0906c3c57f326af4b08c6fcd9a9762c4da8b) associated to the tag you are interested at.

**Comment by Scotty-Trees** [comment]
Awesome that's some good tips to know for the next time I may need to attempt this, I'll bookmark that and keep it in my notes, very useful, thank you again for the assistance.
